version: '3'
services:
  login-service:
    build:
      context: ./components/login-signup
      dockerfile: Dockerfile
    container_name: login-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/FarhanDb
    depends_on:
      - mongo
    networks:
      - my-network

  student-service:
    build:
      context: ./components/student
      dockerfile: Dockerfile
    container_name: student-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network

  react-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - login-service
      - student-service
    networks:
      - my-network

volumes:
  mongo_data:

networks:
  my-network:
    driver: bridge
