services:
  - type: web
    name: my-express-backend
    env: node
    region: global
    plan: free
    buildCommand: |
      npm install                           # Install backend dependencies
      cd client && npm install              # Install frontend dependencies
      cd client && npm run build            # Build the React app
    startCommand: npm run dev               # Run both frontend and backend concurrently
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://fk510199:MRAzJmU69Miz0A8u@cluster0.7j2xk.mongodb.net/FarhanDb
      - key: PORT
        value: 8000
